name: deploy to test instance
on:
  push:
    branches: [ dev ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_TEST }}
        username: ${{ secrets.USERNAME_TEST }}
        key: ${{ secrets.CICD_SECRET_TEST }}
        port: ${{ secrets.PORT_TEST }}
        script: |
          cd /apps/githubworkflows/
          sudo rm -rf dwh-portal
          sudo mkdir dwh-portal
          cd
          git config --global --add safe.directory /apps/githubworkflows/dwh-portal      
          cd /apps/githubworkflows/dwh-portal
          git clone -b dev https://github.com/palladiumkenya/dwh-portal.git .
          sudo cp /apps/githubworkflows/dwh-portal/.env.production /apps/githubworkflows/dwh-portal/
          sudo chown -R cicd:cicd /apps/githubworkflows/dwh-portal
          git status
          yarn install
          yarn build
          sudo rm -rf /tmp/dwhtest
          sudo mv /var/www/dwhtest /tmp/
          sudo mv build /var/www/
          sudo mv /var/www/build/ /var/www/dwhtest
