name: deploy to production
on:
  push:
    branches: [ prod ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          sudo git config --global --add safe.directory /apps/github-workflows/dwh-portal      
          sudo cd /apps/github-workflows/dwh-portal
          sudo git pull origin prod
          sudo git status
          sudo yarn install
          sudo yarn build
          sudo rm -rf /tmp/dwh
          sudo mv /var/www/dwh /tmp/
          sudo mv build /var/www/dwh
